config/routes.rb
Knowyourpet::Application.routes.draw do

  get '/yourpet', to: redirect('/yourpet/sign_in')
  root :to => redirect('/yourpet')
  get "yourpet/sign_in" => "authentication#sign_in"
  get "yourpet/forgot_password" => "authentication#forgot_password"
  post "yourpet/forgot_password" => "authentication#forgot_password1"
  get "yourpet/reset_password"=> "authentication#reset_password"
  put "yourpet/reset_password"=> "authentication#validate_answer"
  get "yourpet/new_user" => "authentication#new_user"
  get "yourpet/new_pet"  => "authentication#new_pet"
  post "yourpet/sign_in" => "authentication#login"
  get "yourpet/signed_out" => "authentication#signed_out"
  put "yourpet/new_user" => "authentication#register"
  put "yourpet/new_pet"  => "authentication#register_pet"
  post "yourpet/new_user" => "authentication#register"
  post "yourpet/new_pet" => "authentication#register_pet"
  get "yourpet/pet_profile" => "profile#pet_profile"
  get "yourpet/medical_record" => "medicalrecords#show", as: "medical_record"
  get "yourpet/create_complaint" => "profile#create_complaint"
  post "yourpet/create_complaint" => "profile#submit_complaint"
  get "yourpet/admin_view"   =>  "admin#admin_view"
  get "yourpet/view_complaint"   =>  "admin#view_complaint"
  get "yourpet/medical_record" => "medicalrecords#show", as: "medical_record"
  get "yourpet/medical_record/edit" => "medicalrecords#edit", as: "edit_medical_record"
  put "yourpet/medical_record.:id" => "medicalrecords#update", as: "update_medical_record"
  delete "yourpet/medical_record" => "medicalrecords#destroy", as: "delete_medical_record"
  

end

app/models/medical_record.rb
class MedicalRecord < ActiveRecord::Base
  attr_accessible :conditions, :distemper, :pet_id, :rabies
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_filter :set_medical_record, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
    respond_with(@medical_record)
  end


  def edit
  end

  def update
    @medical_record.update_attributes(params[:medical_record])
    redirect_to medical_record_path
  end

  def destroy
    @medical_record.destroy
    redirect_to yourpet_sign_in_path
  end

  private
    def set_medical_record
      @medical_record = MedicalRecord.where("pet_id = ?", session[:pet_id]).first_or_create do |newMedRecord|
          newMedRecord.pet_id = session[:pet_id]
      end
    end
  end

app/controllers/medicalrecords_controller.rb
class MedicalrecordsController < ApplicationController
  before_filter :set_medical_record, only: [:show, :edit, :update, :destroy]
  #before_filter :check_login, :only => [:show, :edit, :update, :destroy]
  respond_to :html

  def show
    respond_with(@medical_record)
  end


  def edit
  end

  def update
    @medical_record.update_attributes(params[:medical_record])
    redirect_to medical_record_path
  end

  def destroy
    @medical_record.destroy
    redirect_to yourpet_sign_in_path
  end

  private
    def set_medical_record
      @medical_record = MedicalRecord.where("pet_id = ?", session[:pet_id]).first_or_create do |newMedRecord|
          newMedRecord.pet_id = session[:pet_id]
      end
    end
  end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/views/medicalrecords/_form.html.erb
<%= form_for(@medical_record) do |f| %>
  <% if @medical_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
      <% @medical_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :rabies %><br />
    <%= f.date_select :rabies %>
  </div>
  <div class="field">
    <%= f.label :distemper %><br />
    <%= f.date_select :distemper %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br />
    <%= f.text_area :conditions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicalrecords/edit.html.erb
<h1>Editing medical_record</h1>
<%= link_to 'Sign out', :yourpet_signed_out, :id => "Sign_out", :name => "Sign_out", :class => "linkstyle2" %>
<%= render 'form' %>

<%= link_to 'Back', medical_record_path %>

app/views/medicalrecords/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Medical Records </h1>
<%= link_to 'Sign out', :yourpet_signed_out, :id => "Sign_out", :name => "Sign_out", :class => "linkstyle2" %>
<p>
  <b>Rabies:</b>
  <%= @medical_record.rabies %>
</p>

<p>
  <b>Distemper:</b>
  <%= @medical_record.distemper %>
</p>

<p>
  <b>Conditions:</b>
  <%= @medical_record.conditions %>
</p>


<%= link_to 'Edit', edit_medical_record_path %> |
<%= link_to 'Back', yourpet_pet_profile_path %>