config/routes.rb
Knowyourpet::Application.routes.draw do

  get '/yourpet', to: redirect('/yourpet/sign_in')
  root :to => redirect('/yourpet')
  get "yourpet/sign_in" => "authentication#sign_in"
  get "yourpet/forgot_password" => "authentication#forgot_password"
  post "yourpet/forgot_password" => "authentication#forgot_password1"
  get "yourpet/reset_password"=> "authentication#reset_password"
  put "yourpet/reset_password"=> "authentication#validate_answer"
  get "yourpet/new_user" => "authentication#new_user"
  get "yourpet/new_pet"  => "authentication#new_pet"
  post "yourpet/sign_in" => "authentication#login"
  get "yourpet/signed_out" => "authentication#signed_out"
  put "yourpet/new_user" => "authentication#register"
  put "yourpet/new_pet"  => "authentication#register_pet"
  post "yourpet/new_user" => "authentication#register"
  post "yourpet/new_pet" => "authentication#register_pet"
  get "yourpet/pet_profile" => "profile#pet_profile"
  get "yourpet/medical_record" => "medicalrecords#show", as: "medical_record"
  get "yourpet/create_complaint" => "profile#create_complaint"
  post "yourpet/create_complaint" => "profile#submit_complaint"
  get "yourpet/admin_view"   =>  "admin#admin_view"
  get "yourpet/view_complaint"   =>  "admin#view_complaint"
  get "yourpet/medical_record" => "medicalrecords#show", as: "medical_record"
  get "yourpet/medical_record/edit" => "medicalrecords#edit", as: "edit_medical_record"
  put "yourpet/medical_record.:id" => "medicalrecords#update", as: "update_medical_record"
  delete "yourpet/medical_record" => "medicalrecords#destroy", as: "delete_medical_record"
  

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def sign_in
    @user = User.new
  end

  def login
    username= params[:user][:username]
    password = params[:user][:password]
    user = User.authenticate_by_username(username, password)
    if user
      session[:user_id] = user.id
      #pom = PetOfMonth.petid
      pom = "Dally the Rottwieller"
      flash[:notice] = "Pet of the month: #{pom}."
      if username == "admin" && password == "admin"
         redirect_to :yourpet_admin_view
      else
         redirect_to :yourpet_pet_profile
      end
    else
      flash.now[:error] = 'Please check your username and password.'
      render :action => "sign_in"
    end
  end

  def signed_out
    # clear the authentication toke when the user manually signs out
     user = User.find_by_id(session[:user_id])

     if user
       #update_authentication_token(user, nil)
       user.save
       session[:user_id] = nil
       flash[:notice] = "You have been signed out."
       redirect_to :yourpet_sign_in
     else
       redirect_to :yourpet_sign_in   
     end
  end
  def new_user
     @user = User.new
  end

  def register
    @user = User.new(params[:user])
    
    if @user.valid?
     @user.save     
     session[:user_id] = @user.id
     flash[:notice] = 'Welcome.'
     redirect_to :yourpet_new_pet
    else
     render :action => "new_user"
    end
  end

  def new_pet
    @pet = Pet.new
  end

  def register_pet
    @pet = Pet.new (params[:pet])
    
    if @pet.valid?
      @pet.save
      session[:pet_id] = @pet.id
      @user_id=session[:user_id]
      @user=User.find(@user_id)
      @user.update_attribute(:petid , @pet.id)
      redirect_to :yourpet_pet_profile
    else
      render :action => "new_pet"
    end
  end

   def checkQuestion
     question = User.get_security_question(params[:username])
     
  end
   def forgot_password
     @user = User.new
  end
  def forgot_password1
    @username=params[:user][:username]
    @user = User.where("username = ?", @username).first
    
    if @user.nil?
      flash[:notice] = "Unknown User"
      redirect_to :yourpet_forgot_password
    else
      session[:user_id] = @user.id
      redirect_to :yourpet_reset_password
    end
  end
  def reset_password
      @user=User.find(session[:user_id])
      @user.securityAnswer = ""
  end
  def validate_answer
      @user=User.find(session[:user_id])
      @securityAnswer = params[:user][:securityAnswer]
      @mat=@user.securityAnswer
      if @mat==@securityAnswer
         flash[:notice] = "#{@user.username}, your password is #{@user.password}" 
         redirect_to :yourpet_sign_in
      else
         flash[:notice] = "Your answer is wrong"
         redirect_to :yourpet_reset_password
      end
  end
end

app/views/authentication/forgot_password.html.haml
%h1 Forgot Password
= form_for @user, :as => :user, :url => yourpet_forgot_password_path(@user) do |f|
  %p
    = f.label 'username:'
    %br/
    = f.text_field :username
  %p
    = f.submit 'Next Screen',:id=>"forgot", :name=> "forgot"

app/views/authentication/new_pet.html.haml
%h1 Sign Up Your Pet!
= form_for @pet, :as => :pet, :url => yourpet_new_pet_path, :method => :put do |f|
  %p
    = f.label 'petname'
    %br/
    = f.text_field :petname
    = show_field_error(@pet, :petname)
  %p
    = f.label 'breed'
    = f.text_field :breed
  %p
    = f.label 'color'
    = f.text_field :color
  %p
    = f.label 'interest'
    = f.text_field :interest
  %p
    = f.label 'description'
    = f.text_field :description
  %p
    = f.label 'gender'
    = f.text_field :gender
  %p
    = f.label 'DOB'
    = f.date_select :dob
  %p
    = f.submit 'Submit', :name=>'newpet',:id=> 'newpet'

app/views/authentication/new_user.html.haml
%h1 Sign Up
= form_for @user, :as => :user, :url => yourpet_new_user_path, :method => :put do |f|
  %p
    = f.label 'username:'
    = f.text_field :username
    = show_field_error(@user, :username)
  %p
    = f.label 'email:'
    = f.text_field :email
    = show_field_error(@user, :email)
  %p
    = f.label 'first_name:'
    = f.text_field :first_name
  %p
    = f.label 'last_name:'
    = f.text_field :last_name
  %p
    = f.label 'password:'
    = f.password_field :password
    = show_field_error(@user, :password)
  %p
    = f.label 'password confirmation:'
    = f.password_field :password_confirmation
  %p
    = f.label 'SecurityQuestion:'
    = f.text_field :securityQuestion
  %p
    = f.label 'SecurityAnswer:'
    = f.text_field :securityAnswer
  %p
    = f.submit 'Next-->',:id => "newuser", :name => "newuser"

app/views/authentication/reset_password.haml
%h2 Reset Password
= form_for @user, :as => :user, :url => yourpet_reset_password_path, :method => :put do |f|
  %p
    = f.label 'Security Question: ' + :user.securityQuestion
    %br/
    = f.text_field :securityAnswer
  %p
    = f.submit 'Reset Password'

app/views/authentication/reset_password.html.haml
%h1 Reset Password
= form_for @user, :as => :user, :url => yourpet_reset_password_path do |f|
  %p
    = f.label 'Security Question: ' + @user.securityQuestion
    %br/
    = f.text_field :securityAnswer
  %p
    = f.submit 'Reset Password',:id=> "resetpassword", :name=> "resetpassword"

app/views/authentication/sign_in.html.haml
%h1 Know Your Pet
= form_for @user, :as => :user, :url => yourpet_sign_in_path(@user) do |f|
  %p
    = f.label 'username:'
    = f.text_field :username
    %br/
  %p
    = f.label 'password:'
    = f.password_field :password
    %br/
  %p
    = f.submit 'Sign In',:id => "user_signin", :name => "user_signin", :class => "ButtonStyle"
  %p
    = link_to "Sign up", :yourpet_new_user, :id => "user_signup", :name => "user_signup"
  %p
    = link_to 'Forgot Your Password?', :yourpet_forgot_password, :id => "user_forgotpassword", :name => "user_forgotpassword"